import { Header } from "../components/Header";
import { Widget } from "../components/Widget";

import { Tab } from '@headlessui/react'

export function Home() {
    return (
        <div className="h-screen w-scree">
            <Header />
            <Widget />
            <div className="w-full h-[80vh] flex items-center justify-start flex-col">
                <Tab.Group>
                    <Tab.List className="bg-[#101010] w-2/3 h-[10%] flex items-center justify-center mt-7 rounded-md">
                        <Tab className="w-full h-full rounded-md outline-none">Baixa</Tab>
                        <Tab className="w-full h-full rounded-md outline-none">Média</Tab>
                        <Tab className="w-full h-full rounded-md outline-none">Alta</Tab>
                    </Tab.List>
                    <Tab.Panels className="bg-[#2D2D2D] w-2/4 h-5/6 mt-10 overflow-y-scroll scrollbar-thumb-zinc-700 scrollbar-track-transparent scrollbar-thin">
                        <Tab.Panel>Content 1</Tab.Panel>
                        <Tab.Panel>Content 2</Tab.Panel>
                        <Tab.Panel>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                            <span>Content 3</span>
                        </Tab.Panel>
                    </Tab.Panels>
                </Tab.Group>
            </div>
        </div>
    )
}